route:
    receiver: 'slack'

receivers:
    - name: 'slack'
      slack_configs:
          - send_resolved: true
            username: 'example-user'
            channel: '#example-channel'
            api_url: 'https://hooks.slack.com/services/111111111/222222222/333333333333333333333333'
