version: '3.9'
volumes:
  prometheus_data: {}
  grafana_data: {}
networks:
  front-tier: null
  back-tier: null
services:
  prometheus:
    image: docker.io/prom/prometheus:v2.55.0
    healthcheck:
      test:
      - CMD
      - wget
      - --spider
      - -q
      - http://localhost:9090/-/healthy
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
    - ./prometheus/:/etc/prometheus/
    - prometheus_data:/prometheus
    command:
    - --config.file=/etc/prometheus/config.yml
    - --storage.tsdb.path=/prometheus
    - --web.console.libraries=/usr/share/prometheus/console_libraries
    - --web.console.templates=/usr/share/prometheus/consoles
    - --web.enable-lifecycle
    ports:
    - 9090:9090
    networks:
    - back-tier
    restart: always
  grafana:
    image: docker.io/grafana/grafana:11.3.0
    healthcheck:
      test:
      - CMD
      - wget
      - --spider
      - -q
      - http://localhost:3000/api/health
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
    - prometheus
    ports:
    - 3000:3000
    volumes:
    - grafana_data:/var/lib/grafana:rw
    - ./grafana/provisioning/:/etc/grafana/provisioning/:ro
    env_file:
    - ./grafana/config.env
    networks:
    - back-tier
    - front-tier
    restart: always
  alertmanager:
    image: docker.io/prom/alertmanager:v0.27.0
    ports:
    - 9093:9093
    volumes:
    - ./alertmanager/:/etc/alertmanager/
    networks:
    - back-tier
    restart: always
    command:
    - --config.file=/etc/alertmanager/config.yml
    - --storage.path=/alertmanager
  blackbox_exporter:
    image: docker.io/prom/blackbox-exporter:v0.25.0
    dns: 1.1.1.1
    restart: always
    ports:
    - 9115:9115
    volumes:
    - ./blackbox:/blackbox
    networks:
    - back-tier
    command: --config.file=/blackbox/config.yml
  nginx:
    image: docker.io/nginx:1.27.2
    ports:
    - 8080:80
    networks:
    - back-tier
    - front-tier
    volumes:
    - ./nginx/html:/usr/share/nginx/html:ro
    - ./nginx/etc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
