{
 "title": "AWS ELB Application Load Balancer by Target Group",
 "description": "Visualize AWS ELB Application Load Balancer and Target Group metrics",
 "tags": [ "cloudwatch" ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "cloudwatch" },
   { "name": "region", "label": "Region", "query": "regions()" },
   {
    "name": "loadbalancername",
    "label": "LoadBalancerName",
    "query": "dimension_values($region,AWS/ApplicationELB,ActiveConnectionCount,LoadBalancer)"
   },
   {
    "name": "targetgroup",
    "label": "Target Group",
    "query": "dimension_values($region,AWS/ApplicationELB,HealthyHostCount,TargetGroup, {\"LoadBalancer\":\"$loadbalancername\"})"
   }
  ]
 },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Healthy Hosts ($loadbalancername)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "TargetGroup": "$targetgroup" },
     "metricName": "HealthyHostCount",
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Minimum"
    }
   ]
  },
  {
   "title": "Unhealthy Hosts ($targetgroup)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "TargetGroup": "$targetgroup" },
     "metricName": "UnHealthyHostCount",
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Avg. TargetResponseTime ($targetgroup)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "dimensions": { "TargetGroup": "$targetgroup" },
     "metricName": "TargetResponseTime",
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  { "title": "ELB and TargetGroup Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "RequestCount / TargetResponseTime ($loadbalancername)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dimensions": { "LoadBalancer": "$loadbalancername" },
     "metricName": "TargetResponseTime",
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "application": { "filter": "" },
     "dimensions": { "LoadBalancer": "$loadbalancername" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "RequestCount",
     "namespace": "AWS/ApplicationELB",
     "options": {
      "showDisabledItems": false
     },
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "RequestCount / TargetResponseTime ($targetgroup)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dimensions": { "LoadBalancer": "$loadbalancername", "TargetGroup": "$targetgroup" },
     "metricName": "TargetResponseTime",
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "application": { "filter": "" },
     "dimensions": { "LoadBalancer": "$loadbalancername", "TargetGroup": "$targetgroup" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "RequestCount",
     "namespace": "AWS/ApplicationELB",
     "options": {
      "showDisabledItems": false
     },
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "HTTPCode_Target ($loadbalancername)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "LoadBalancer": "$loadbalancername" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "HTTPCode_Target_5XX_Count",
     "namespace": "AWS/ApplicationELB",
     "options": {
      "showDisabledItems": false
     },
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "application": { "filter": "" },
     "dimensions": { "LoadBalancer": "$loadbalancername" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "HTTPCode_Target_4XX_Count",
     "namespace": "AWS/ApplicationELB",
     "options": {
      "showDisabledItems": false
     },
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "application": { "filter": "" },
     "dimensions": { "LoadBalancer": "$loadbalancername" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "HTTPCode_Target_3XX_Count",
     "namespace": "AWS/ApplicationELB",
     "options": {
      "showDisabledItems": false
     },
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "application": { "filter": "" },
     "dimensions": { "LoadBalancer": "$loadbalancername" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "HTTPCode_Target_2XX_Count",
     "namespace": "AWS/ApplicationELB",
     "options": {
      "showDisabledItems": false
     },
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "HTTPCode_Target ($targetgroup)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "LoadBalancer": "$loadbalancername", "TargetGroup": "$targetgroup" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "HTTPCode_Target_5XX_Count",
     "namespace": "AWS/ApplicationELB",
     "options": {
      "showDisabledItems": false
     },
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "application": { "filter": "" },
     "dimensions": { "LoadBalancer": "$loadbalancername", "TargetGroup": "$targetgroup" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "HTTPCode_Target_4XX_Count",
     "namespace": "AWS/ApplicationELB",
     "options": {
      "showDisabledItems": false
     },
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "application": { "filter": "" },
     "dimensions": { "LoadBalancer": "$loadbalancername", "TargetGroup": "$targetgroup" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "HTTPCode_Target_3XX_Count",
     "namespace": "AWS/ApplicationELB",
     "options": {
      "showDisabledItems": false
     },
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "application": { "filter": "" },
     "dimensions": { "LoadBalancer": "$loadbalancername", "TargetGroup": "$targetgroup" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "HTTPCode_Target_2XX_Count",
     "namespace": "AWS/ApplicationELB",
     "options": {
      "showDisabledItems": false
     },
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "HTTPCode_ELB ($loadbalancername)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "LoadBalancer": "$loadbalancername" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "HTTPCode_ELB_3XX_Count",
     "namespace": "AWS/ApplicationELB",
     "options": {
      "showDisabledItems": false
     },
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "application": { "filter": "" },
     "dimensions": { "LoadBalancer": "$loadbalancername" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "HTTPCode_ELB_4XX_Count",
     "namespace": "AWS/ApplicationELB",
     "options": {
      "showDisabledItems": false
     },
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "application": { "filter": "" },
     "dimensions": { "LoadBalancer": "$loadbalancername" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "HTTPCode_ELB_5XX_Count",
     "namespace": "AWS/ApplicationELB",
     "options": {
      "showDisabledItems": false
     },
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "HTTPCode_TargetGroup ($targetgroup)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "LoadBalancer": "$loadbalancername", "TargetGroup": "$targetgroup" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "HTTPCode_Target_3XX_Count",
     "namespace": "AWS/ApplicationELB",
     "options": {
      "showDisabledItems": false
     },
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "application": { "filter": "" },
     "dimensions": { "LoadBalancer": "$loadbalancername", "TargetGroup": "$targetgroup" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "HTTPCode_Target_4XX_Count",
     "namespace": "AWS/ApplicationELB",
     "options": {
      "showDisabledItems": false
     },
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "application": { "filter": "" },
     "dimensions": { "LoadBalancer": "$loadbalancername", "TargetGroup": "$targetgroup" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "HTTPCode_Target_5XX_Count",
     "namespace": "AWS/ApplicationELB",
     "options": {
      "showDisabledItems": false
     },
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "ELB Only Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "ConnectionCount (ELB Only)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "application": { "filter": "" },
       "dimensions": { "LoadBalancer": "$loadbalancername" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "metricName": "ActiveConnectionCount",
       "namespace": "AWS/ApplicationELB",
       "options": {
        "showDisabledItems": false
       },
       "queryMode": "Metrics",
       "region": "$region",
       "statistic": "Average"
      },
      {
       "application": { "filter": "" },
       "dimensions": { "LoadBalancer": "$loadbalancername" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "metricName": "NewConnectionCount",
       "namespace": "AWS/ApplicationELB",
       "options": {
        "showDisabledItems": false
       },
       "queryMode": "Metrics",
       "region": "$region",
       "statistic": "Average"
      },
      {
       "application": { "filter": "" },
       "dimensions": { "LoadBalancer": "$loadbalancername" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "metricName": "RejectedConnectionCount",
       "namespace": "AWS/ApplicationELB",
       "options": {
        "showDisabledItems": false
       },
       "queryMode": "Metrics",
       "region": "$region",
       "statistic": "Average"
      },
      {
       "application": { "filter": "" },
       "dimensions": { "LoadBalancer": "$loadbalancername" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "metricName": "TargetConnectionErrorCount",
       "namespace": "AWS/ApplicationELB",
       "options": {
        "showDisabledItems": false
       },
       "queryMode": "Metrics",
       "region": "$region",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "ConsumedLBCapacityUnits / ConsumedLCUs / ProcessedBytes (ELB Only)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "application": { "filter": "" },
       "dimensions": { "LoadBalancer": "$loadbalancername" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "metricName": "ConsumedLBCapacityUnits",
       "namespace": "AWS/ApplicationELB",
       "options": {
        "showDisabledItems": false
       },
       "queryMode": "Metrics",
       "region": "$region",
       "statistic": "Average"
      },
      {
       "application": { "filter": "" },
       "dimensions": { "LoadBalancer": "$loadbalancername" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "metricName": "ProcessedBytes",
       "namespace": "AWS/ApplicationELB",
       "options": {
        "showDisabledItems": false
       },
       "queryMode": "Metrics",
       "region": "$region",
       "statistic": "Average"
      },
      {
       "application": { "filter": "" },
       "dimensions": { "LoadBalancer": "$loadbalancername" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "metricName": "ConsumedLCUs",
       "namespace": "AWS/ApplicationELB",
       "options": {
        "showDisabledItems": false
       },
       "queryMode": "Metrics",
       "region": "$region",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "TLSNegotiationErrorCount (ELB Only)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "application": { "filter": "" },
       "dimensions": { "LoadBalancer": "$loadbalancername" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "metricName": "TargetTLSNegotiationErrorCount",
       "namespace": "AWS/ApplicationELB",
       "options": {
        "showDisabledItems": false
       },
       "queryMode": "Metrics",
       "region": "$region",
       "statistic": "Sum"
      },
      {
       "application": { "filter": "" },
       "dimensions": { "LoadBalancer": "$loadbalancername" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "metricName": "ClientTLSNegotiationErrorCount",
       "namespace": "AWS/ApplicationELB",
       "options": {
        "showDisabledItems": false
       },
       "queryMode": "Metrics",
       "region": "$region",
       "statistic": "Sum"
      }
     ]
    },
    {
     "title": "RuleEvaluations (ELB Only)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "application": { "filter": "" },
       "dimensions": { "LoadBalancer": "$loadbalancername" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "metricName": "RuleEvaluations",
       "namespace": "AWS/ApplicationELB",
       "options": {
        "showDisabledItems": false
       },
       "queryMode": "Metrics",
       "region": "$region",
       "statistic": "Sum"
      }
     ]
    },
    {
     "title": "Auth (ELB Only)",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "application": { "filter": "" },
       "dimensions": { "LoadBalancer": "$loadbalancername" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "metricName": "ELBAuthError",
       "namespace": "AWS/ApplicationELB",
       "options": {
        "showDisabledItems": false
       },
       "queryMode": "Metrics",
       "region": "$region",
       "statistic": "Sum"
      },
      {
       "application": { "filter": "" },
       "dimensions": { "LoadBalancer": "$loadbalancername" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "metricName": "ELBAuthFailure",
       "namespace": "AWS/ApplicationELB",
       "options": {
        "showDisabledItems": false
       },
       "queryMode": "Metrics",
       "region": "$region",
       "statistic": "Sum"
      },
      {
       "application": { "filter": "" },
       "dimensions": { "LoadBalancer": "$loadbalancername" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "metricName": "ELBAuthSuccess",
       "namespace": "AWS/ApplicationELB",
       "options": {
        "showDisabledItems": false
       },
       "queryMode": "Metrics",
       "region": "$region",
       "statistic": "Sum"
      },
      {
       "application": { "filter": "" },
       "dimensions": { "LoadBalancer": "$loadbalancername" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "metricName": "ELBAuthRefreshTokenSuccess",
       "namespace": "AWS/ApplicationELB",
       "options": {
        "showDisabledItems": false
       },
       "queryMode": "Metrics",
       "region": "$region",
       "statistic": "Sum"
      },
      {
       "application": { "filter": "" },
       "dimensions": { "LoadBalancer": "$loadbalancername" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "metricName": "ELBAuthUserClaimsSizeExceeded",
       "namespace": "AWS/ApplicationELB",
       "options": {
        "showDisabledItems": false
       },
       "queryMode": "Metrics",
       "region": "$region",
       "statistic": "Sum"
      },
      {
       "application": { "filter": "" },
       "dimensions": { "LoadBalancer": "$loadbalancername" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "metricName": "ELBAuthLatency",
       "namespace": "AWS/ApplicationELB",
       "options": {
        "showDisabledItems": false
       },
       "queryMode": "Metrics",
       "region": "$region",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "IPv6 (ELB Only)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 75 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "application": { "filter": "" },
       "dimensions": { "LoadBalancer": "$loadbalancername" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "metricName": "IPv6RequestCount",
       "namespace": "AWS/ApplicationELB",
       "options": {
        "showDisabledItems": false
       },
       "queryMode": "Metrics",
       "region": "$region",
       "statistic": "Sum"
      },
      {
       "application": { "filter": "" },
       "dimensions": { "LoadBalancer": "$loadbalancername" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "metricName": "IPv6ProcessedBytes",
       "namespace": "AWS/ApplicationELB",
       "options": {
        "showDisabledItems": false
       },
       "queryMode": "Metrics",
       "region": "$region",
       "statistic": "Sum"
      }
     ]
    }
   ]
  }
 ]
}